commerce_payment.commerce_payment_gateway.plugin.smartpay:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_account:
      type: string
      label: 'Merchant account'
    skin_code:
      type: string
      label: 'Skin code'
    test_shared_secret:
      type: string
      label: 'Test shared secret'
    live_shared_secret:
      type: string
      label: 'Live shared secret'